### ISSUE TITLE
fleetctl convert doesn't work with multiline queries

### ISSUE THREAD

**Issue by kliseb** [kolide/fleet#1828]
### What version of `fleet` are you using (`fleet version --full`)?
$ ./build/fleet version --full
fleet - version 2.0.0-rc1-10-gd9038f3-dirty
  branch: 	master
  revision: 	d9038f37f47397c403b2d55f723857270f9d4ba3
  build date: 	2018-06-12T15:39:55Z
  build user: 	brandonklise
  go version: 	go1.10.2
### What operating system are you using?
osx 10.13.4
### What did you do?
I ran `$ ./build/fleetctl convert -f /private/var/osquery/packs/osx-attacks.conf` to convert the osquery json pack to yaml.
### What did you expect to see?
The typical output of the `fleetctl convert` command, such as
```yaml
---
apiVersion: v1
kind: pack
spec:
  name: osx
  queries:
  - description: (http://www.intego.com/mac-security-blog/new-mac-trojan-discovered-related-to-syria/)
    interval: 3600
    name: Leverage-A_1
    query: Leverage-A_1
    version: 1.4.5
  targets:
    labels: null
---
apiVersion: v1
kind: query
spec:
  description: (http://www.intego.com/mac-security-blog/new-mac-trojan-discovered-related-to-syria/)
  name: Leverage-A_1
  query: select * from launchd where path like '%UserEvent.System.plist';
```
### What did you see instead?
`invalid character '\n' in string escape code`
This is due to the osquery pack having multiline queries:
```json
"queries": {
    "WireLurker": {
      "query" : "select * from launchd where \
        name = 'com.apple.machook_damon.plist' OR \
        name = 'com.apple.globalupdate.plist' OR \
        name = 'com.apple.appstore.plughelper.plist' OR \
        name = 'com.apple.MailServiceAgentHelper.plist' OR \
        name = 'com.apple.systemkeychain-helper.plist' OR \
        name = 'com.apple.periodic-dd-mm-yy.plist';",
      "interval" : "3600",
      "version": "1.4.5",
      "description" : "(https://github.com/PaloAltoNetworks-BD/WireLurkerDetector)",
      "value" : "Artifact used by this malware"
    },
```
