### ISSUE TITLE
FIM config not generating results

### ISSUE THREAD

**Issue by rubenrodr-versia** [kolide/fleet#1846]
Hi,

I have setup fim for linux using fleetctl with the following config:

>    platforms:
      linux:
        decorators:
          interval:
            "3600": SELECT total_seconds AS uptime FROM uptime
          load:
          - SELECT * FROM cpuid
          - SELECT * FROM docker_info
        exclude_paths:
          etc:
          - /etc/redis/%%
        file_paths:
          etc:
          - /etc/%%
        options:
          config_refresh: 60
          disable_events: false
          distributed_interval: 5
          distributed_tls_max_attempts: 3
          docker_socket: /etc/run/docker.sock
          events_expiry: 3600
          events_max: 50000
          events_optimize: true
          logger_plugin: tls
          logger_tls_endpoint: /api/v1/osquery/log
          logger_tls_period: 60
          schedule_timeout: 60

### What version of `fleet` are you using (`fleet version --full`)?
fleet version --full
fleet - version 2.0.0-rc3
  branch:       master
  revision:     8b7edf759db2911030a660aa85cf82615f0f5f4b
  build date:   2018-06-22T00:37:31Z
  build user:   marpaia
  go version:   go1.10.3

fleetctl --version
fleetctl - version 2.0.0-rc3
  branch:       master
  revision:     8b7edf759db2911030a660aa85cf82615f0f5f4b
  build date:   2018-06-22T00:37:51Z
  build user:   marpaia
  go version:   go1.10.3
### What operating system are you using?
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP2
Release:        12.2
Codename:       n/a
### What did you do?
Schedule a query on file_events table for all linux hosts every 30 seconds.
### What did you expect to see?
Updated results log file when creating/deleting a file on /etc
### What did you see instead?
result log file not being updated

**Comment by zwass** [comment]
It doesn't look to me like any of your configuration options are making it to that host. Unless you only provided part of your config file, it looks like you are using invalid syntax (the `platforms` key should be under the `overrides` key if you want to do platform-specific overrides).

Please first take a look at https://github.com/kolide/fleet/blob/master/docs/cli/file-format.md#osquery-configuration-options for the configuration syntax. Try to make your configuration file match the syntax as described in the doc.

If that doesn't work, please provide the (exactly formatted by enclosing with ```) output of `fleetctl get options`. Also more information about the host you are running this query on.

**Comment by rubenrodr-versia** [comment]
Hi,

This is the full config:

```
fleetctl get options
apiVersion: v1
kind: options
spec:
  config:
    decorators:
      always:
      - SELECT user AS username FROM logged_in_users WHERE user <> '' ORDER BY time
        LIMIT 1
      interval:
        "3600": SELECT total_seconds AS uptime FROM uptime
      load:
      - SELECT version FROM osquery_info
      - SELECT uuid AS host_uuid FROM system_info
    options:
      distributed_interval: 3
      distributed_tls_max_attempts: 3
      logger_plugin: tls
      logger_tls_endpoint: /api/v1/osquery/log
      logger_tls_period: 10
  overrides:
    platforms:
      linux:
        decorators:
          interval:
            "3600": SELECT total_seconds AS uptime FROM uptime
          load:
          - SELECT * FROM cpuid
          - SELECT * FROM docker_info
        exclude_paths:
          etc:
          - /etc/redis/%%
        file_paths:
          etc:
          - /etc/%%
        options:
          config_refresh: 60
          disable_events: false
          distributed_interval: 5
          distributed_tls_max_attempts: 3
          docker_socket: /etc/run/docker.sock
          events_expiry: 3600
          events_max: 50000
          events_optimize: true
          logger_plugin: tls
          logger_tls_endpoint: /api/v1/osquery/log
          logger_tls_period: 60
          schedule_timeout: 60
      windows:
        options:
          disable_events: false
          events_expiry: 3600
          events_max: 50000
          events_optimize: true
          windows_event_channels: System,Application,Setup,Security
```
I have the query:
![image](https://user-images.githubusercontent.com/24841626/41893531-4bc9a3a4-791c-11e8-9f8f-a97d7080e377.png)

Included in pack:
![image](https://user-images.githubusercontent.com/24841626/41893546-601d6606-791c-11e8-8b8f-f568c152ccbc.png)


Thanks.
Best regards.

**Comment by zwass** [comment]
Please provide the config with formatting as described in https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by rubenrodr-versia** [comment]
Hi,

I have edited the previous comment.

Thanks.
Best regards.

**Comment by zwass** [comment]
I realized there was a bug in the documentation regarding platform overrides. Please check out my clarification in https://github.com/kolide/fleet/pull/1855 and see if you can get things working as expected.

**Comment by rubenrodr-versia** [comment]
Hi,

I have updated the config with rhel and sles platforms and now is working fine:

```
apiVersion: v1
kind: options
spec:
  config:
    decorators:
      always:
      - SELECT user AS username FROM logged_in_users WHERE user <> '' ORDER BY time
        LIMIT 1
      interval:
        "3600": SELECT total_seconds AS uptime FROM uptime
      load:
      - SELECT version FROM osquery_info
      - SELECT uuid AS host_uuid FROM system_info
    options:
      distributed_interval: 3
      distributed_tls_max_attempts: 3
      logger_plugin: tls
      logger_tls_endpoint: /api/v1/osquery/log
      logger_tls_period: 10
  overrides:
    platforms:
      rhel:
        decorators:
          interval:
            "3600": SELECT total_seconds AS uptime FROM uptime
          load:
          - SELECT * FROM cpuid
          - SELECT * FROM docker_info
        exclude_paths:
          etc:
          - /etc/redis/%%
        file_paths:
          etc:
          - /etc/%%
        options:
          config_refresh: 60
          disable_events: false
          distributed_interval: 5
          distributed_tls_max_attempts: 3
          docker_socket: /etc/run/docker.sock
          events_expiry: 3600
          events_max: 50000
          events_optimize: true
          logger_plugin: tls
          logger_tls_endpoint: /api/v1/osquery/log
          logger_tls_period: 60
          schedule_timeout: 60
      sles:
        decorators:
          interval:
            "3600": SELECT total_seconds AS uptime FROM uptime
          load:
          - SELECT * FROM cpuid
          - SELECT * FROM docker_info
        exclude_paths:
          etc:
          - /etc/redis/%%
        file_paths:
          etc:
          - /etc/%%
        options:
          config_refresh: 60
          disable_events: false
          distributed_interval: 5
          distributed_tls_max_attempts: 3
          docker_socket: /etc/run/docker.sock
          events_expiry: 3600
          events_max: 50000
          events_optimize: true
          logger_plugin: tls
          logger_tls_endpoint: /api/v1/osquery/log
          logger_tls_period: 60
          schedule_timeout: 60
      windows:
        options:
          disable_events: false
          events_expiry: 3600
          events_max: 50000
          events_optimize: true
          windows_event_channels: System,Application,Setup,Security
```

Thanks.
Best regards.
