### ISSUE TITLE
fleetctl apply returns an error for queries containing a colon inside of quotes

### ISSUE THREAD

**Issue by kliseb** [kolide/fleet#1853]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc3-dirty
  branch: 	master
  revision: 	8b7edf759db2911030a660aa85cf82615f0f5f4b
  build date: 	2018-06-25T15:48:50Z
  build user: 	brandonklise
  go version: 	go1.10.2
### What operating system are you using?
macOS 10.13.4
### What did you do?
Attempted to apply a pack and queries to fleet using `fleetctl apply -f verify-compliance.yml`.
### What did you expect to see?
```bash
$ fleetctl apply -f verify-compliance.yml
[+] applied 15 queries
[+] applied 1 packs
```
### What did you see instead?
```bash
$ fleetctl apply -f verify-compliance.yml
error converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context
```
My issue was with the following query: `SELECT * FROM sudoers WHERE rule_details LIKE '%nopasswd: all%';`, in particular the colon in the string `'%nopasswd: all%'`. I tried escaping the colon and using double quotes instead of single quotes, but still had the same result.
Also, the error message was not very helpful in debugging since the error was on line 132, not line 6.

**Comment by zwass** [comment]
I did some tests with our yaml parsing library, and I think you just need to double-quote the entire query (with single quotes around the string in the query). Please let me know if this works.

**Comment by kliseb** [comment]
Applying double quotes around the entire query resulted in `error converting YAML to JSON: yaml: line 5: did not find expected key`.

**Comment by zwass** [comment]
Can you please provide a minimal yaml to repro this?

**Comment by kliseb** [comment]
```yaml
---
apiVersion: v1
kind: pack
spec:
  name: Compliance
  queries:
    - query: allows_sudo_without_password
      name: allows_sudo_without_password
      interval: 3600
  targets:
    labels:
    - 'All Hosts'
---
apiVersion: v1
kind: query
spec:
  name: allows_sudo_without_password
  query: SELECT * FROM sudoers WHERE rule_details LIKE '%nopasswd: all%';
```

**Comment by zwass** [comment]
Surrounding the query in quotes works fine for me. Does this not work for you?

```
---
apiVersion: v1
kind: pack
spec:
  name: Compliance
  queries:
    - query: allows_sudo_without_password
      name: allows_sudo_without_password
      interval: 3600
  targets:
    labels:
    - 'All Hosts'
---
apiVersion: v1
kind: query
spec:
  name: allows_sudo_without_password
  query: "SELECT * FROM sudoers WHERE rule_details LIKE '%nopasswd: all%';"
```
