### ISSUE TITLE
Better log messages - panic: unreachable ?

### ISSUE THREAD

**Issue by devx** [kolide/fleet#1863]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc3
  branch:       master
  revision:     8b7edf759db2911030a660aa85cf82615f0f5f4b
  build date:   2018-06-22T00:37:31Z
  build user:   marpaia
  go version:   go1.10.3

### What operating system are you using?
Linux
Kernel: 4.4.0-130-generic #156-Ubuntu SMP

### What did you do?
fleet prepare db --config=/etc/fleet/fleet_config.yml

MYSQL and redis were verified and working.

Configuration file
```
mysql:
  address: 10.0.2.50:3306
  database: fleet
  username: fleet
  password: fleet
redis:
  address: localhost:6379
auth:
  jwt_key: {rnadom value}
server:
  cert: /etc/ssl/certs/fleet.cert
  key: /etc/ssl/private/fleet.key
logging:
  json: true
```

### What did you expect to see?
Eather migration complete or helpful message to fix issue.

### What did you see instead?
fleet prepare db --config=/etc/fleet/fleet_config.yml
Using config file:  /etc/fleet/fleet_config.yml
panic: unreachable

goroutine 1 [running]:
github.com/kolide/fleet/vendor/github.com/kolide/goose.(*Client).GetDBVersion(0xc42009dd00, 0xc4201f5e00, 0x0, 0x0, 0x0)
        /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/kolide/goose/migrate.go:205 +0x357
github.com/kolide/fleet/server/datastore/mysql.(*Datastore).MigrationStatus(0xc420234820, 0x11, 0xc420230218, 0x5)
        /Users/marpaia/go/src/github.com/kolide/fleet/server/datastore/mysql/mysql.go:134 +0x8d
main.createPrepareCmd.func2(0xc4201b2c80, 0xc420177710, 0x0, 0x1)
        /Users/marpaia/go/src/github.com/kolide/fleet/cmd/fleet/prepare.go:47 +0x132
github.com/kolide/fleet/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201b2c80, 0xc4201776d0, 0x1, 0x1, 0xc4201b2c80, 0xc4201776d0)
        /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
github.com/kolide/fleet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201b2780, 0x0, 0xc4201b3680, 0xc42023012b)
        /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/kolide/fleet/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201b2780, 0xc420161f40, 0x1)
        /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
        /Users/marpaia/go/src/github.com/kolide/fleet/cmd/fleet/main.go:29 +0x1cd
