### ISSUE TITLE
Frontend displays incorrect log type when query created with fleetctl

### ISSUE THREAD

**Issue by zwass** [kolide/fleet#1869]
### What version of `fleet` are you using (`fleet version --full`)?
2.0.0 RC3

### What operating system are you using?
Any

### What did you do?
Schedule a query with `fleetctl`

```
apiVersion: v1
kind: pack
spec:
  id: 1
  name: test
  queries:
  - description: ""
    interval: 10
    name: time
    query: time
  targets:
    labels:
    - All Hosts
```

### What did you expect to see?
Query should display as "Differential" in UI

### What did you see instead?
Query displays as "Differential (Ignore Removals)"
