### ISSUE TITLE
External Data Sinks for OSQuery Results and Status messages

### ISSUE THREAD

**Issue by jrossi** [kolide/fleet#1875]
I am about to spend to much time on planes and as PoC I am planning on adding osquery results logging directly into fleet.  This would allow the results to be processed downstream and outside of fleet. 

Normally I would just reach for kafka and move on, but after looking at the code base I think NATs https://github.com/nats-io/gnatsd might be a slightly better option.  Here is why: 

- NATs  installation is easier 
- using NATs in place of Redis for web sockets is much simpler
- code is much simpler 

With that being said ignoring kafka is crazy, but for a PoC I think simple is better.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrossi** [comment]
#1899 was created as Proof of Concept of this.  I open the PR well before it's done to gather feedback early :)

**Comment by jrossi** [comment]
I have a much better understand of how Fleet works, and how the code is put together after doing my POC in #1899.  With this I would like to proposal the following as a method for integration of external data sinks for osquery results/status.  

## Proposal

Rather then adding more server configuration that needs to be completed on hosts running fleet.  It would be simpler to add the routing of data to sinks using apiVersioned yaml specification.  

This would keep the server configuration very simple while also allowing a simple path users that upgrade.  Here is an example of what the config would look like.  
```
apiVersion: v1
kind: output
spec:
  name: windows_kafka_queue
  descriptions: All windows hosts request pro
  type: kafka 
  kafka:
     topic: fleet.windows.results
     brokers: 127.0.0.1:9018
  match:
    - type: results
    - platform: windows
---
apiVersion: v1
kind: output
spec:
  name: unix_nats_queue
  descriptions: All
  type: kafka 
  kafka:
     topic: fleet.unix.{.PlatForm}
     brokers: 127.0.0.1:9018
  match:
    - type: results
    - platform: !windows
---
apiVersion: v1
kind: output
spec:
  name: local_results
  descriptions: All
  type: file
  file:
     path: /tmp/fleet_results
     log_rotate: false
  match:
    - type: results
---
apiVersion: v1
kind: output
spec:
  name: local_status
  descriptions: All
  type: file
  file:
     path: /tmp/fleet_status
     log_rotate: false
  match:
    - type: status
```
