### ISSUE TITLE
Platform issue

### ISSUE THREAD

**Issue by rubenrodr-versia** [kolide/fleet#1914]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc4
  branch:       master
  revision:     71e8e3917eb77058721c9f7ad6e4d3e3704717a2
  build date:   2018-08-14T23:56:00Z
  build user:   zwass
  go version:   go1.10.2
### What operating system are you using?
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP2
Release:        12.2
Codename:       n/a
### What did you do?
Created pack:
```
---
apiVersion: v1
kind: pack
spec:
  name: Test1
  description: TEST Pack.
  targets:
    labels:
      - 'SLES 12 SP2'
  queries:
    - query: authorized_keys
      name: authorized_keys
      platform: sles
      interval: 30
      shard: 100
      removed: true
    - query: dns_resolvers
      name: dns_resolvers
      interval: 30
      shard: 100
      removed: true
```
Created a label for SLES 12 SP2:
```
# fleetctl get l
+--------------+----------+--------------------------------+--------------------------------+
| SLES 12 SP2  |          |                                | SELECT 1 from os_version WHERE |
|              |          |                                | name='SLES' AND major='12' AND |
|              |          |                                | minor='2';                     |
+--------------+----------+--------------------------------+--------------------------------+
```
The platform icon is the same as "All":
![image](https://user-images.githubusercontent.com/24841626/44857949-2b261c80-ac71-11e8-91de-6f1e7d8abd13.png)

![screen shot 08-30-18 at 04 16 pm](https://user-images.githubusercontent.com/24841626/44858181-b7d0da80-ac71-11e8-9e6e-b518c22f02ec.PNG)

### What did you expect to see?
authorized_keys query executed as the targeted host platform is sles:
```
osquery> select * from os_version
    ...> ;
+------+---------+-------+-------+-------+-------+----------+---------------+----------+
| name | version | major | minor | patch | build | platform | platform_like | codename |
+------+---------+-------+-------+-------+-------+----------+---------------+----------+
| SLES | 12-SP2  | 12    | 2     | 0     |       | sles     |               |          |
+------+---------+-------+-------+-------+-------+----------+---------------+----------+
```
### What did you see instead?
Only the query dns resolvers is being executed.
If i remove platform option from the query or change it to linux works fine.
