### ISSUE TITLE
max_open_conns settings

### ISSUE THREAD

**Issue by rubenrodr-versia** [kolide/fleet#2058]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.1.2
  branch:       master
  revision:     eb212116dc7433717e441f83848df300a55c96f7
  build date:   2019-05-30T19:05:25Z
  build user:   zwass
  go version:   go1.11.5

### What operating system are you using?
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP2
Release:        12.2
Codename:       n/a

### What did you do?
Set max_open_conns on config file to 2000
```
mysql:
  address: 127.0.0.1:3306
  database: kolide
  username: xxxxxx
  password: xxxxxx
  max_open_conns: 2000
  max_idle_conns: 500
```

### What did you expect to see?
max_open_conns: 2000

### What did you see instead?
```
fleet config_dump
mysql:
  address: localhost:3306
  username: xxxxxx
  password: xxxxxx
  database: xxxxxx
  tls_cert: ""
  tls_key: ""
  tls_ca: ""
  tls_server_name: ""
  tls_config: ""
  max_open_conns: 50
  max_idle_conns: 50
```

**Comment by zwass** [comment]
You need to add `--config` path if you want Fleet to load a config file. Otherwise it will use CLI flags, env vars, and defaults.

**Comment by rubenrodr-versia** [comment]
I have fleet running as systemd service, using --config to load configuration from file
```
# systemctl status kolide
● kolide.service - Kolide Server
   Loaded: loaded (/usr/lib/systemd/system/kolide.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-06-06 15:52:14 CEST; 16h ago
 Main PID: 23081 (fleet)
    Tasks: 19 (limit: 512)
   CGroup: /system.slice/kolide.service
           └─23081 /bin/fleet serve --config /etc/kolide/kolide.yml
```
but running fleet config_dump shows max_open_conns value different from config file.

**Comment by rubenrodr-versia** [comment]
My fault, I was not running config_dump with --config file, which shows the correct values:
```
# fleet config_dump --config /etc/kolide/kolide.yml
Using config file:  /etc/kolide/kolide.yml
mysql:
  address: 127.0.0.1:3306
  username: xxxxxxx
  password: xxxxxxx
  database: kolide
  tls_cert: ""
  tls_key: ""
  tls_ca: ""
  tls_server_name: ""
  tls_config: ""
  max_open_conns: 2000
  max_idle_conns: 500
```
