### ISSUE TITLE
Hosts disconnections

### ISSUE THREAD

**Issue by rubenrodr-versia** [kolide/fleet#2062]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.1.2
  branch:       master
  revision:     eb212116dc7433717e441f83848df300a55c96f7
  build date:   2019-05-30T19:05:25Z
  build user:   zwass
  go version:   go1.11.5

### What operating system are you using?
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP2
Release:        12.2
Codename:       n/a

### What did you do?
Add more hosts (total 230)

### What did you expect to see?
No disconnections

### What did you see instead?
Every 3-5 seconds hosts disconnects and reconnects again

**Comment by rubenrodr-versia** [comment]
I have fleet running behind an apache reverse proxy with websockets enabled:
```
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           wss://127.0.0.1:8080/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           https://127.0.0.1:8080/$1 [P,L]
  ProxyPassReverse / https://127.0.0.1:8080/
```
I get the following errors on apache ssl logs:

```
[Tue Jun 18 07:40:10.214193 2019] [proxy_http:error] [pid 21064] (70008)Partial results are valid but processing is incomplete: [client 172.22.41.200:50478] AH02609: read request body failed to 127.0.0.1:8080 (127.0.0.1) from 172.22.41.200 ()
[Tue Jun 18 07:40:10.214233 2019] [proxy_http:error] [pid 21064] [client 172.22.41.200:50478] AH01097: pass request body failed to 127.0.0.1:8080 (127.0.0.1) from 172.22.41.200 ()
[Tue Jun 18 07:44:30.845669 2019] [proxy_http:error] [pid 14615] (70008)Partial results are valid but processing is incomplete: [client 172.22.41.200:50552] AH02609: read request body failed to 127.0.0.1:8080 (127.0.0.1) from 172.22.41.200 ()
[Tue Jun 18 07:44:30.845734 2019] [proxy_http:error] [pid 14615] [client 172.22.41.200:50552] AH01097: pass request body failed to 127.0.0.1:8080 (127.0.0.1) from 172.22.41.200 ()
[Tue Jun 18 08:08:18.635627 2019] [proxy_http:error] [pid 12919] (70008)Partial results are valid but processing is incomplete: [client 10.30.5.105:41044] AH02609: read request body failed to 127.0.0.1:8080 (127.0.0.1) from 10.30.5.105 ()
[Tue Jun 18 08:08:18.635675 2019] [proxy_http:error] [pid 12919] [client 10.30.5.105:41044] AH01097: pass request body failed to 127.0.0.1:8080 (127.0.0.1) from 10.30.5.105 ()
```

I don't see errors on kolide_status.json log or in the mysql logs
These are my fleet settings:
```
mysql:
  address: 127.0.0.1:3306
  database: kolide
  username: xxxxxxxxx
  password: xxxxxxxxx
  max_open_conns: 5000
  max_idle_conns: 300
redis:
  address: 127.0.0.1:6379
server:
  address: 127.0.0.1:8080
  cert: /etc/kolide/certs/kolide.crt
  key: /etc/kolide/certs/kolide.key
session:
  duration: 12h
auth:
  jwt_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
logging:
  json: true
  disable_banner: true
osquery:
  result_log_file: /var/log/kolide/kolide_result.json
  status_log_file: /var/log/kolide/kolide_status.json
  enable_log_rotation: true
```
