### ISSUE TITLE
Fleet is not able to connect to MySQL over SSL only with CA certificate specified

### ISSUE THREAD

**Issue by myfoxtail** [kolide/fleet#2124]
I'm getting the following error message trying to run `fleet prepare db`:

```
Error creating db connection: register TLS config for mysql: load mysql client cert and key: open : no such file or directory
```

My config contains just a path to a CA certificate.

```
mysql:
        address: mydb.somewhere.com:3306
        database: kolide
        username: fleet
        password: teelf
        tls_ca: ./blah.crt.pem
        tls_config: true
```

It looks like it's trying to get client key and certificate files, but I don't need them in order to connect to the database. Is there any way to solve this problem?
