### ISSUE TITLE
Empty snapshots from osqueryd are being logged in fleet

### ISSUE THREAD

**Issue by myfoxtail** [kolide/fleet#2128]
Fleet server version on 18.04.1-Ubuntu

```
fleet - version 2.3.0
  branch: 	master
  revision: 	bc9782e9b0c431ce8c24552861f5527fb0f4c390
  build date: 	2019-08-14T18:55:06Z
  build user: 	zwass
  go version: 	go1.12.8
```

osquery is running on Mac Catalina.

Following all settings from the documentation osquery and fleet seem to work fine. Scheduled queries are being executed and I can see it in verbose logs of osquery and `results.log` file.

**Though** inside results log every snapshot is empty:

```
{
  "snapshot": [],
  "action": "snapshot",
  "name": "pack/Mac General Pack/Disk encryption check",
  "hostIdentifier": "xxx",
  "calendarTime": "Fri Nov  1 04:36:58 2019 UTC",
  "unixTime": 1572583018,
  "epoch": 0,
  "counter": 0,
  "logNumericsAsNumbers": false,
  "decorations": {
    "host_uuid": "xxx",
    "hostname": "mac"
  }
}
```

Here are flags I'm running osquery with:

```
sudo /usr/local/bin/osqueryd \
  --enroll_secret_path=/var/osquery/enroll_secret \
  --tls_server_certs=/var/osquery/xxx.pem \
  --tls_hostname=xxx:8080 \
  --disable_events=false \
  --host_identifier=uuid \
  --enroll_tls_endpoint=/api/v1/osquery/enroll \
  --config_plugin=tls \
  --config_tls_endpoint=/api/v1/osquery/config \
  --config_refresh=10 \
  --disable_distributed=false \
  --distributed_plugin=tls \
  --distributed_interval=3 \
  --distributed_tls_max_attempts=3 \
  --distributed_tls_read_endpoint=/api/v1/osquery/distributed/read \
  --distributed_tls_write_endpoint=/api/v1/osquery/distributed/write \
  --logger_plugin=tls \
  --force=true --verbose --tls_dump \
  --logger_tls_endpoint=/api/v1/osquery/log \
  --logger_tls_period=60
```

Fleet config:

```
mysql:
        address: xxx:3306
        database: kolide
        username: xxx
        password: xxx
        tls_ca: xxx.pem
redis:
        address: xxx
auth:
        jwt_key: xxx
server:
        address: 0.0.0.0:8080
        tls: true
        cert: fullchain.pem
        key: privkey.pem
logging:
        json: true
filesystem:
        status_log_file: /var/log/osquery/status.log
        result_log_file: /var/log/osquery/result.log
        enable_log_rotation: true  
```

I've tried host_identifier as `hostname` and `uuid`, it does not make a difference.
