### ISSUE TITLE
fleetctl tries to process commented out YAML separator

### ISSUE THREAD

**Issue by ianmuscat** [kolide/fleet#2245]
### What version of `fleetctl` are you using (`fleetclt -v`)?
```
fleetctl - version 2.6.0
  branch: 	master
  revision: 	d3849d8fe1ea841d34a19e5cc06bfe62fc8dfd2d
  build date: 	2020-03-24T17:28:05Z
  build user: 	zwass
  go version: 	go1.13.4
```
### What operating system are you using?
```
uname -v
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
```
### What did you do?

I tried to apply the following *valid* YAML document using `fleetctl apply -f filename.yaml
```
---
apiVersion: v1
kind: pack
spec:
  name: test
  targets:
    labels: null
  queries:
  - description: ""
    interval: 86400
    name: crontab-snapshot
    platform: linux
    query: crontab-snapshot
    snapshot: true
# ---
#
---
apiVersion: v1
kind: query
spec:
  description: ""
  name: crontab-snapshot
  query: SELECT * FROM crontab;
```
### What did you expect to see?
```
[+] applied 1 queries
[+] applied 1 packs
```
### What did you see instead?

fleetctl returned the following error.
```
no spec field on "" document
```

Removing, the YAML document separator `---` in the comment does not trigger this behavior. Additionally, the error with an empty string makes it hard to debug what's going on (especially in large YAML documents).
