### ISSUE TITLE
Can't change options dynamically

### ISSUE THREAD

**Issue by QDSD0** [kolide/fleet#2246]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.6.0
### What operating system are you using?
CentOS Linux release 7.8.2003

### What did you do?
1.  start fleet with this options
```
apiVersion: v1
kind: options
spec:
  config:
    decorators:
      load:
      - SELECT uuid AS host_uuid FROM system_info;
      - SELECT hostname AS hostname FROM system_info;
    options:
      config_refresh: 3
      disable_distributed: false
      distributed_interval: 10
      distributed_plugin: tls
      distributed_tls_max_attempts: 3
      logger_plugin: tls
      logger_tls_endpoint: /api/v1/osquery/log
      logger_tls_period: 10
      pack_delimiter: /
  overrides: {}

```

2  fleetctl apply -f my.yml
```
apiVersion: v1
kind: options
spec:
  config:
    decorators:
      load:
      - SELECT uuid AS host_uuid FROM system_info;
      - SELECT hostname AS hostname FROM system_info;
    options:
      config_refresh: 10
      disable_distributed: false
      distributed_interval: 10
      distributed_plugin: tls
      distributed_tls_max_attempts: 3
      logger_tls_endpoint: /api/v1/osquery/log
      logger_tls_period: 10
      pack_delimiter: /
      logger_kafka_brokers: ssl://192.168.84.130:9093
      logger_kafka_topic: test
      logger_kafka_compression: gzip
      logger_kafka_acks: 1
      logger_plugin: kafka_producer
      tls_client_cert: /usr/local/apps/kafka/pki/certificate.pem
      tls_server_certs: /usr/local/apps/kafka/pki/CARoot.pem
      tls_client_key: /usr/local/apps/kafka/pki/client-key.pem

```

### What did you expect to see?

kafka gets messages.

### What did you see instead?
kafka didn't get messages.
but the osquery_options table in mysql is changed.

if i restart fleet,the kafka will get message.
